# Site wide configuration

title: "Lick Innovation"
description: "The Lick Innovation team blog"
logo: logo-120.png # 120x120 px default image used for Twitter summary card
teaser: site-teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

collections:
  products:
    output: true

defaults:
  -
    scope:
      path:"/_posts/blog/"
      type:"posts"
    values:
      layout:"article"
      permalink:"/blog/:title"

  -
    scope:
      path:"/_posts/work/"
      type:"posts"
    values:
      layout:"article"
      permalink:"/work/:title"

  -
    scope:
      path:""
      type:"products"
    values:
      layout:"media"
      
# Prose.io configuration

prose:
  metadata:
    media: "/images"
      _posts:
        - name: "published"
          field:
            label: "Published"
            element: "checkbox"
            value: "true"
        - name: "layout"
          field:
            label: "Layout"
            element: "text"
            value: "article"
        - name: "title"
          field:
            label: "Title"
            element: "text"
          value: "A awesome Headline!"
    _products:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "media"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: Lick Creative
keep_files: ["roost.html", "roost_manifest.json", "roost_worker.js"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
