# Site wide configuration

title: Lick Innovation
description: The Lick Innovation team blog
logo: logo-120.png # 120x120 px default image used for Twitter summary card
teaser: site-teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

collections:
  products:
    output: true

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: Lick Creative

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "roost.html", "roost_worker.js", "roost_manifest.json"]
