# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lick Innovation
tagline:          Our team blog
url:              http://lickinnovation.com
paginate:         1
baseurl:          /
author:
  name:           Oliver Phillips
  url:            https://twitter.com/wearelick
  email:          innovation@lickcreative.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/gignar/gignar.github.io
