# Site wide configuration

title: "Lick Innovation"
description: "The Lick Innovation team blog"
logo: logo-120.png # 120x120 px default image used for Twitter summary card
teaser: site-teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

collections:
  products:
    output: true

defaults:
  -
    scope:
      path:"/_posts/blog/"
      type:"posts"
    values:
      layout:"article"
      permalink:"/blog/:title"

  -
    scope:
      path:"/_posts/work/"
      type:"posts"
    values:
      layout:"article"
      permalink:"/work/:title"

  -
    scope:
      path:"/_products"
      type:"products"
    values:
      layout:"media"

# Prose.io configuration

prose:
# rooturl: ''
  siteurl: 'http://lickinnovation.com'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - _layouts
    - _includes
    - _data
    - _sass
    - _templates
    - css
    - fonts
    - js
    - .editorconfig
    - .gitignore
    - .jshintrc
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - LICENSE
    - README.md
    - _octopress.yml
    - apple-touch-icon-precomposed.png
    - atom.xml
    - favicon.ico
    - package.json
    - roost.html
    - roost_manifest.json
    - roost_worker.js
  metadata:
    _posts:
      - name: "published"
        field:
            label: "Published"
            element: "checkbox"
            value: "true"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "text"
          value: "article"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Blog"
              value: "blog"
            - name: "Products"
              value: "products"
            - name: "Work"
              value: "work"
    _products:
      - name: "published"
        field:
            label: "Published"
            element: "checkbox"
            value: "true"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "multiselect"
          options:
          - name: "Article"
            value: "article"
          - name: "Media"
            value: "media"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Blog"
              value: "blog"
            - name: "Products"
              value: "products"
            - name: "Work"
              value: "work"

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: Lick Creative
keep_files: ["roost.html", "roost_manifest.json", "roost_worker.js"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
